version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./endurance/data:/var/lib/postgresql/data
      - ./endurance/input:/input
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
