---
title: "ANN Benchmarks"
author: "Chip Lynch"
date: "2/23/2021"
output: pdf_document
---


## writing output to results/random-xs-20-euclidean.png
Found cached result
  0:                                                                     TrilatExpand        1.000      401.899
Found cached result
  1:                                                                    Trilateration        1.000       25.971
Found cached result
  2:                                                              TrilaterationApprox        0.585       71.236
Computing knn metrics
  3:                                                             TrilaterationExpand2        1.000     1411.711
Found cached result
  4:                                                           BallTree(leaf_size=40)        1.000     3040.686
Found cached result
  5:                                                           BallTree(leaf_size=10)        1.000     3974.894
Found cached result
  6:                                                         BallTree(leaf_size=1000)        1.000     2224.275
Found cached result
  7:                                                          BallTree(leaf_size=100)        1.000     2561.925
Found cached result
  8:                                                          BallTree(leaf_size=400)        1.000     2265.526
Found cached result
  9:                                                          BallTree(leaf_size=200)        1.000     2352.948
Found cached result
 10:                                                           BallTree(leaf_size=20)        1.000     3532.328
Found cached result
 11:                                                                     BruteForce()        1.000      670.163


## writing output to results/glove-25-angular.png
Computing knn metrics
  0:                                                 FaissIVF(n_list=2048, n_probe=1)        0.416     1938.482
Computing knn metrics
  1:                                                FaissIVF(n_list=4096, n_probe=50)        0.965     1098.394
Computing knn metrics
  2:                                                 FaissIVF(n_list=64, n_probe=200)        1.000       35.085
Computing knn metrics
  3:                                                   FaissIVF(n_list=64, n_probe=1)        0.664     1123.371
Computing knn metrics
  4:                                               FaissIVF(n_list=1024, n_probe=200)        1.000      164.781
Computing knn metrics
  5:                                                   FaissIVF(n_list=32, n_probe=1)        0.704      714.849
Computing knn metrics
  6:                                               FaissIVF(n_list=4096, n_probe=100)        0.988      733.391
Computing knn metrics
  7:                                                 FaissIVF(n_list=8192, n_probe=1)        0.334     1703.636
Computing knn metrics
  8:                                                 FaissIVF(n_list=32, n_probe=200)        1.000       35.108
Computing knn metrics
  9:                                                 FaissIVF(n_list=512, n_probe=50)        0.995      305.273
Computing knn metrics
 10:                                                FaissIVF(n_list=128, n_probe=100)        1.000       43.439
Computing knn metrics
 11:                                                  FaissIVF(n_list=32, n_probe=10)        0.995      108.414
Computing knn metrics
 12:                                               FaissIVF(n_list=2048, n_probe=200)        0.999      295.694
Computing knn metrics
 13:                                                FaissIVF(n_list=8192, n_probe=50)        0.946     1201.676
Computing knn metrics
 14:                                                  FaissIVF(n_list=256, n_probe=1)        0.554     1742.011
Computing knn metrics
 15:                                                FaissIVF(n_list=512, n_probe=100)        0.999      166.827
Computing knn metrics
 16:                                                 FaissIVF(n_list=64, n_probe=100)        1.000       35.081
Computing knn metrics
 17:                                               FaissIVF(n_list=4096, n_probe=200)        0.997      441.810
Computing knn metrics
 18:                                                FaissIVF(n_list=256, n_probe=200)        1.000       44.869
Computing knn metrics
 19:                                               FaissIVF(n_list=8192, n_probe=100)        0.978      932.471
Computing knn metrics
 20:                                                FaissIVF(n_list=1024, n_probe=10)        0.896     1358.564
Computing knn metrics
 21:                                                 FaissIVF(n_list=8192, n_probe=5)        0.658     1709.966
Computing knn metrics
 22:                                                 FaissIVF(n_list=128, n_probe=10)        0.971      354.258
Computing knn metrics
 23:                                                FaissIVF(n_list=8192, n_probe=10)        0.776     1569.960
Computing knn metrics
 24:                                                   FaissIVF(n_list=64, n_probe=5)        0.948      363.314
Computing knn metrics
 25:                                                 FaissIVF(n_list=128, n_probe=50)        1.000       83.435
Computing knn metrics
 26:                                                  FaissIVF(n_list=128, n_probe=1)        0.607     1517.637
Computing knn metrics
 27:                                                 FaissIVF(n_list=1024, n_probe=1)        0.467     1894.326
Computing knn metrics
 28:                                                   FaissIVF(n_list=32, n_probe=5)        0.970      203.792
Computing knn metrics
 29:                                                 FaissIVF(n_list=256, n_probe=50)        0.998      169.421
Computing knn metrics
 30:                                                  FaissIVF(n_list=256, n_probe=5)        0.884      997.154
Computing knn metrics
 31:                                                FaissIVF(n_list=512, n_probe=200)        1.000       87.226
Computing knn metrics
 32:                                                 FaissIVF(n_list=512, n_probe=10)        0.925      990.031
Computing knn metrics
 33:                                                FaissIVF(n_list=1024, n_probe=50)        0.990      495.363
Computing knn metrics
 34:                                                 FaissIVF(n_list=1024, n_probe=5)        0.805     1648.008
Computing knn metrics
 35:                                                FaissIVF(n_list=2048, n_probe=50)        0.979      826.074
Computing knn metrics
 36:                                                 FaissIVF(n_list=256, n_probe=10)        0.952      605.637
Computing knn metrics
 37:                                               FaissIVF(n_list=2048, n_probe=100)        0.994      465.453
Computing knn metrics
 38:                                                 FaissIVF(n_list=4096, n_probe=1)        0.375     1878.121
Computing knn metrics
 39:                                                FaissIVF(n_list=256, n_probe=100)        1.000       88.562
Computing knn metrics
 40:                                                  FaissIVF(n_list=128, n_probe=5)        0.918      591.155
Computing knn metrics
 41:                                                 FaissIVF(n_list=32, n_probe=100)        1.000       35.103
Computing knn metrics
 42:                                                 FaissIVF(n_list=4096, n_probe=5)        0.708     1772.210
Computing knn metrics
 43:                                                  FaissIVF(n_list=512, n_probe=5)        0.845     1353.636
Computing knn metrics
 44:                                               FaissIVF(n_list=8192, n_probe=200)        0.993      615.649
Computing knn metrics
 45:                                                FaissIVF(n_list=4096, n_probe=10)        0.819     1693.549
Computing knn metrics
 46:                                               FaissIVF(n_list=1024, n_probe=100)        0.997      300.927
Computing knn metrics
 47:                                                FaissIVF(n_list=128, n_probe=200)        1.000       34.741
Computing knn metrics
 48:                                                  FaissIVF(n_list=64, n_probe=50)        1.000       44.832
Computing knn metrics
 49:                                                  FaissIVF(n_list=64, n_probe=10)        0.986      205.624
Computing knn metrics
 50:                                                FaissIVF(n_list=2048, n_probe=10)        0.858     1608.728
Computing knn metrics
 51:                                                 FaissIVF(n_list=2048, n_probe=5)        0.757     1812.419
Computing knn metrics
 52:                                                  FaissIVF(n_list=32, n_probe=50)        1.000       35.020
Computing knn metrics
 53:                                                  FaissIVF(n_list=512, n_probe=1)        0.507     1873.798
Found cached result
 54:                                                             TrilaterationExpand2        1.000        6.125
Found cached result
 55:                                                          BallTree(leaf_size=200)        1.000        8.084
Found cached result
 56:                                                                     BruteForce()        1.000        3.765
