---
output:
  pdf_document: default
  html_document: default
---
$$\\[0.5in]$$

# NETWORK ADEQUACY

The trilateration index was originally designed to improve efficiency of the "network adequacy" (NA) problem for health care.  Network adequacy is a common legal requirement for medicare or insurance companies with constraints such as:

* 90% of members must live within 50 miles of a covered emergency room
* 80% of female members over the age of 13 must live within 25 miles of a covered OB/GYN
* 80% of members under the age of 16 must live within 25 miles of a covered pediatrician
* etc.

Note that these are all illustrative examples; the real "Medicare Advantage Network Adequacy Criteria Guidance" document for example, is a 75 page document.

Similar requirements, legal or otherwise, show up in cellular network and satellite communication technology (numbers are illustrative):

* Maximize the number of people living within 10 miles of a 5G cell tower
* 100% of all major highways should be within 5 miles of a 4G cell tower
* There must be at least 2 satellites within 200 km of a point 450 km directly above every ground station for satellite network connectivity at any given time
* There must be at least 1 satellite with access to a ground station within 50 km of a point 450 km directly above as many households as possible at any given time

The nearest-neighbor problem was called the "Post-Office Problem" in early incarnations, and the system of post offices lends itself to a similar construction:
* Ensure that all US Postal addresses are within range of a post office 

and so forth.


## Formalization of Network Adequacy

Since we could not find formal mathematical definitions in existing literature, we now formalize the concept of "Network Adequacy" here as:

Given a non-empty set of points $P$ and a non-empty set of query points $Q$ in a metric space $M$ (where $P \cap Q$ comprises the 'network'), the network is 'completely adequate' for a distance $d$ and a distance function $D(a, b)$ describing the distance between points $a$ and $b$ for $a \in M$ and $b \in M$ if for every point $q$ (where $q \in Q$) $\exists$ at least one point $p$ ($p \in P$) $\ni D(p, q) <= d$.  Otherwise the network is 'inadequate'.

We call a single point $q$ 'adequate' itself, if it satisfies the same condition -- i.e. $\exists$ at least one point $p$ ($p \in P$) $D(p, q) <= d$.


### Network Adequacy Percent

If, within $P$, we consider the largest subset $P' \in P$ where $P'$ is 'completely adequate',  then $P$ has a "Network Adequacy Percent (NAP)" of $|P'|/|P|$.  Note that $P'$ can be defined (identically) as the union of all 'adequate' points $p \in P$.

### Network Adequacy Threshold
We can generalize this slightly more by describing a network as 'adequate with threshold $T$' by introducing a percent $T$ ($0<=T<=1$) such that the same network is adequate if at least $T*|Q|$ (or $T$ percent of points in $Q$) are individually 'adequate'.

Another way of saying this is that the network is 'adequate with threshold $T$' if the Network Adequacy Percent ${NAP} > T$.

In this case, if $T == 1$ we have the original case.  If $T == 0$ we have a trivial case where the network is always adequate (even if $Q$ and/or $P$ are empty, which is generally disallowed).

### k-Network Adequacy (kNA)

Similarly to the $kNN$ extension of nearest-neighbor search, where we want the $k$ nearest values, a $k$-network adequacy problem could be stated:

Given $P$ and $Q$ as before, a network is 'completely k-adequate' for a given $k$ if $\exists$ at least $k$ points $p \in P$ $\ni D(p, q) <= d$.  Otherwise the network is 'k-inadequate'.

Similarly, a single point $q$ is 'k-adequate' itself, if it satisfies the same condition -- i.e. $\exists$ at least $k$ points $p \in P \ni D(p, q) <= d$.  Otherwise the point is 'k-inadequate'.
