---
title: "Simple Distance Functions"
author: "Chip Lynch"
date: "1/31/2021"
output: pdf_document
---

## Simple distance functions

Before jumping into [Network Adequacy] and [Nearest Neighbor] algorithms let's look at the core usage of the trilateration data structure and its use in simple distance functions.

What we mean by 'simple distance functions' is one of the following primitive functions common to SQL or map related software libraries:

* $D(p, q)$: returns the distance between points p and q
* $Within(d, q, P)$:  returns the set of all points in $P$ within distance $d$ of query point $q$
* $AnyWithin(d, q, P)$: returns a boolean result - True if $Within(d, q, P)$ is non-empty; False otherwise

### Distance Function

How can we use the Trilateration Index ($TI$) to improve the performance of a single distance function $D(p, q)$?  In the simplest case, we cannot... the construction of the $TI$ structures requires three distance functions to be calculated each for $p$ and $q$ (to the three fixed reference points).

However, for large datasets with fixed points where many distances need to be calculated between them, particularly if the distance function itself is computationally intensive (such as geospatial distances on an accurate ellipsoid model of earth) [@Lambert1942 pp 125–130], we can use the $TI$ structure to create approximate distances, and provide upper and lower bounds on exact values.

For example, let's take our sample data:

```{r sampleDistance, fig.align="center", echo=FALSE}
```
