---
title: "Multilateration Index - Masters Thesis"
author: |
  | Chip Lynch
  | University of Louisville
date: "07/20/2021"
output:
  pdf_document:
    toc: true
    number_sections: true
    extra_dependencies: ["float"]
  html_document: default
institute: University of Louisville
bibliography: references.bib
geometry: "left=1.5in,right=1in,top=1in,bottom=0.5in"
header-includes: 
  - \renewcommand\refname{References}
  - \usepackage{placeins}
  - \usepackage{setspace}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'H')
# knitr::opts_chunk$set(fig.pos = 'H')
# knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
# Keep figures from floating - thank you https://gist.github.com/burchill/8873d2ade156b27e92a238a774ce2758:
knitr::knit_hooks$set(plot = function (x, options) {
  float_correct <- function(f, y, opts)  {
    if (is.null(opts$regfloat) || opts$regfloat==FALSE)
      paste0(f(y, opts), "\n\n\\FloatBarrier\n")
    else
      f(y, opts)
  }
  if (!is.null(options$out.width) || !is.null(options$out.height) ||
      !is.null(options$out.extra) || options$fig.align != "default" ||
      !is.null(options$fig.subcap)) {
    if (is.null(options$fig.scap))
      options$fig.scap = NA
    return(float_correct(knitr:::hook_plot_tex, x, options))
  }
  return(float_correct(knitr:::hook_plot_md_base, x, options))
})
```

\newpage

\doublespacing
```{r child = 'Abstract.rmd'}
```

\newpage
```{r child = 'Introduction.rmd'}
```

\newpage

```{r child = 'ReviewOfLiterature.rmd'}
```

\newpage

```{r child = 'NetworkAdequacyDefinition.rmd'}
```

\newpage

```{r child = 'MultilaterationIndex.rmd'}
```

\newpage

```{r child = 'MathTheory.rmd'}
```

\newpage

```{r child = 'Experiment.rmd'}
```

\newpage

```{r child = 'ConclusionsAndFutureWork.rmd'}
```


\newpage

```{r child = 'Appendix.rmd'}
```
